/** Generado por scripts/build-landings.js — no editar a mano */
window.NH_LANDING_ORDER = [
  "vender-piso-ciutat-vella-barcelona",
  "vender-eixample",
  "vender-gracia",
  "vender-les-corts",
  "vender-piso-barceloneta",
  "vender-piso-born-barcelona",
  "vender-piso-gotic-barcelona",
  "vender-piso-raval-barcelona",
  "vender-poblenou",
  "vender-sants",
  "vender-sarria",
  "vender-horta",
  "vender-nou-barris",
  "vender-sant-antoni",
  "vender-sant-gervasi",
  "vender-sant-marti",
  "vender-badalona",
  "vender-el-clot-la-sagrera-barcelona",
  "vender-l-hospitalet",
  "vender-poble-sec",
  "vender-sant-andreu",
  "vender-esplugues",
  "vender-cornella",
  "vender-sant-just-sant-joan-despi",
  "comprar-piso-les-corts-barcelona",
  "comprar-piso-eixample-barcelona",
  "comprar-piso-gracia-barcelona",
  "comprar-piso-sant-antoni-barcelona",
  "comprar-piso-poble-sec-barcelona",
  "comprar-piso-sant-gervasi-barcelona",
  "comprar-piso-sant-marti-barcelona",
  "comprar-piso-sants-barcelona",
  "comprar-piso-sarria-barcelona",
  "comprar-piso-badalona-barcelona",
  "comprar-piso-esplugues-barcelona",
  "comprar-piso-horta-barcelona",
  "comprar-piso-l-hospitalet-barcelona",
  "comprar-piso-nou-barris-barcelona",
  "comprar-piso-poblenou-barcelona",
  "comprar-piso-sant-andreu-barcelona",
  "cuanto-vale-mi-piso-barcelona",
  "vender-piso-alquilado-barcelona",
  "vender-piso-antes-comprar-otro-barcelona",
  "vender-piso-herencia-barcelona",
  "vender-piso-hipoteca-pendiente-barcelona",
  "vender-piso-inquilino-vencer-barcelona",
  "vender-piso-okupado-barcelona",
  "vender-piso-separacion-divorcio-barcelona",
  "vender-piso-traslado-barcelona",
  "vender-segunda-residencia-barcelona",
  "inmobiliaria-precio-fijo-badalona-barcelona",
  "inmobiliaria-precio-fijo-barcelona",
  "inmobiliaria-precio-fijo-ciutat-vella-barcelona",
  "inmobiliaria-precio-fijo-cornella-barcelona",
  "inmobiliaria-precio-fijo-eixample-barcelona",
  "inmobiliaria-precio-fijo-el-clot-barcelona",
  "inmobiliaria-precio-fijo-esplugues-barcelona",
  "inmobiliaria-precio-fijo-gracia-barcelona",
  "inmobiliaria-precio-fijo-horta-barcelona",
  "inmobiliaria-precio-fijo-l-hospitalet-barcelona",
  "inmobiliaria-precio-fijo-les-corts-barcelona",
  "inmobiliaria-precio-fijo-nou-barris-barcelona",
  "inmobiliaria-precio-fijo-poble-sec-barcelona",
  "inmobiliaria-precio-fijo-poblenou-barcelona",
  "inmobiliaria-precio-fijo-sant-andreu-barcelona",
  "inmobiliaria-precio-fijo-sant-antoni-barcelona",
  "inmobiliaria-precio-fijo-sant-gervasi-barcelona",
  "inmobiliaria-precio-fijo-sants-barcelona",
  "inmobiliaria-precio-fijo-sarria-barcelona",
  "vender-piso-rapido-barcelona",
  "vender-piso-sin-exclusividad-barcelona",
  "venta-piso-economica-barcelona",
  "venta-piso-economica-eixample-barcelona",
  "venta-piso-economica-gracia-barcelona",
  "venta-piso-economica-horta-barcelona",
  "venta-piso-economica-l-hospitalet-barcelona",
  "venta-piso-economica-les-corts-barcelona",
  "venta-piso-economica-poblenou-barcelona",
  "venta-piso-economica-sant-antoni-barcelona",
  "venta-piso-economica-sant-marti-barcelona",
  "venta-piso-economica-sants-barcelona",
  "venta-piso-economica-sarria-barcelona",
  "vender-como-particular-badalona-barcelona",
  "vender-como-particular-barcelona",
  "vender-como-particular-ciutat-vella-barcelona",
  "vender-como-particular-cornella-barcelona",
  "vender-como-particular-eixample-barcelona",
  "vender-como-particular-esplugues-barcelona",
  "vender-como-particular-gracia-barcelona",
  "vender-como-particular-horta-barcelona",
  "vender-como-particular-l-hospitalet-barcelona",
  "vender-como-particular-les-corts-barcelona",
  "vender-como-particular-poblenou-barcelona",
  "vender-como-particular-sant-andreu-barcelona",
  "vender-como-particular-sant-antoni-barcelona",
  "vender-como-particular-sant-marti-barcelona",
  "vender-como-particular-sants-barcelona",
  "vender-como-particular-sarria-barcelona",
  "nuevahabitat-vs-agencia-tradicional-barcelona",
  "nuevahabitat-vs-clikalia-barcelona",
  "nuevahabitat-vs-fotocasa-particular",
  "nuevahabitat-vs-housfy-barcelona",
  "nuevahabitat-vs-idealista-particular",
  "vender-por-tu-cuenta-vs-nuevahabitat-barcelona",
  "comprar-piso-barcelona"
];
window.NH_LANDING_CLUSTERS = {
  barrio: { label: 'Por barrio', slugs: [] },
  situacion: { label: 'Por situación', slugs: [] },
  intencion: { label: 'Guías vendedor', slugs: [] },
  particular: { label: 'Vender como particular', slugs: [] },
  comparativa: { label: 'Comparativas', slugs: [] },
  comprador: { label: 'Comprar', slugs: [] },
};
window.NH_LANDINGS = {
  "vender-badalona": {
    "slug": "vender-badalona",
    "cluster": "barrio",
    "barrio": "Badalona",
    "footerLabel": "Vender en Badalona",
    "zonas": [
      "Centre",
      "Gorg",
      "Montigalà",
      "La Salut",
      "Sant Roc",
      "Artigues"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/interior11.jpg",
    "cardTeaser": "¿Vendes en Badalona? Mercado ~2.650–3.100 €/m²."
  },
  "vender-cornella": {
    "slug": "vender-cornella",
    "cluster": "barrio",
    "barrio": "Cornellà de Llobregat",
    "footerLabel": "Vender en Cornellà",
    "zonas": [
      "Centre",
      "Sant Ildefons",
      "Almeda",
      "Riera",
      "Gavarra"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/barcelona1.jpeg",
    "cardTeaser": "¿Vendes en Cornellà de Llobregat? Mercado ~2.600–3.100 €/m²."
  },
  "vender-eixample": {
    "slug": "vender-eixample",
    "cluster": "barrio",
    "barrio": "Eixample",
    "footerLabel": "Vender en el Eixample",
    "zonas": [
      "Eixample Derecho",
      "Eixample Esquerre",
      "Sagrada Família",
      "Passeig de Gràcia",
      "Fort Pienc",
      "Sant Antoni"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": true,
    "cardImage": "imagenes/eixample1.jpg",
    "cardTeaser": "¿Vendes tu piso en el Eixample? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-el-clot-la-sagrera-barcelona": {
    "slug": "vender-el-clot-la-sagrera-barcelona",
    "cluster": "barrio",
    "barrio": "El Clot - La Sagrera",
    "footerLabel": "Vender en El Clot / La Sagrera",
    "zonas": [
      "El Clot",
      "La Sagrera",
      "Sant Martí de Provençals",
      "Congrés"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/santmarti1.webp",
    "cardTeaser": "¿Vendes tu piso en El Clot, La Sagrera o Sant Martí de Provençals? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-esplugues": {
    "slug": "vender-esplugues",
    "cluster": "barrio",
    "barrio": "Esplugues de Llobregat",
    "footerLabel": "Vender en Esplugues",
    "zonas": [
      "Can Vidalet",
      "Can Sant Joan",
      "Centre",
      "Finestrelles",
      "Les Malloles"
    ],
    "priority": 0.855,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/esplugues1.jpg",
    "cardTeaser": "¿Vendes en Esplugues? Mercado ~3.200–3.800 €/m²."
  },
  "vender-gracia": {
    "slug": "vender-gracia",
    "cluster": "barrio",
    "barrio": "Gràcia",
    "footerLabel": "Vender en Gràcia",
    "zonas": [
      "Vila de Gràcia",
      "Camp d'en Grassot",
      "Vallcarca",
      "Penitents"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/gracia1.jpg",
    "cardTeaser": "¿Vendes tu piso en Gràcia? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-horta": {
    "slug": "vender-horta",
    "cluster": "barrio",
    "barrio": "Horta-Guinardó",
    "footerLabel": "Vender en Horta-Guinardó",
    "zonas": [
      "Horta centre",
      "Montbau",
      "Vall d'Hebron",
      "La Teixonera",
      "El Carmel"
    ],
    "priority": 0.87,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/horta1.jpg",
    "cardTeaser": "¿Vendes en Horta-Guinardó, Montbau o Vall d'Hebron? Mercado ~3.900–4.300 €/m²."
  },
  "vender-l-hospitalet": {
    "slug": "vender-l-hospitalet",
    "cluster": "barrio",
    "barrio": "L'Hospitalet",
    "footerLabel": "Vender en L'Hospitalet",
    "zonas": [
      "Centre",
      "Bellvitge",
      "Pubilla Cases",
      "Granvia L'H",
      "Santa Eulàlia"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/hospitalet1.jpg",
    "cardTeaser": "¿Vendes en L'Hospitalet? Mercado ~2.750–3.200 €/m²."
  },
  "vender-les-corts": {
    "slug": "vender-les-corts",
    "cluster": "barrio",
    "barrio": "Les Corts",
    "footerLabel": "Vender en Les Corts",
    "zonas": [
      "Numància",
      "Zona Universitaria",
      "Pedralbes",
      "Les Corts centre"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": true,
    "cardImage": "imagenes/lescorts1.jpg",
    "cardTeaser": "¿Vendes tu piso en Les Corts? NuevaHabitat: plataforma para vendedores con honorarios fijos de 3.000€ + IVA."
  },
  "vender-nou-barris": {
    "slug": "vender-nou-barris",
    "cluster": "barrio",
    "barrio": "Nou Barris",
    "footerLabel": "Vender en Nou Barris",
    "zonas": [
      "Verdum",
      "Roquetes",
      "Trinitat Vella",
      "Porta",
      "Torre Baró"
    ],
    "priority": 0.87,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/noubarris1.jpg",
    "cardTeaser": "¿Vendes tu piso en Nou Barris, Roquetes o Verdum? Honorarios fijos 3.000€ + IVA."
  },
  "vender-piso-barceloneta": {
    "slug": "vender-piso-barceloneta",
    "cluster": "barrio",
    "barrio": "Barceloneta",
    "footerLabel": "Vender en la Barceloneta",
    "zonas": [
      "Passeig Marítim",
      "Plaça del Mar",
      "Carrer de Sant Carles",
      "Barceloneta playa"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/barcelona2.jpg",
    "cardTeaser": "¿Vendes tu piso en la Barceloneta? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-piso-born-barcelona": {
    "slug": "vender-piso-born-barcelona",
    "cluster": "barrio",
    "barrio": "Born",
    "footerLabel": "Vender en el Born",
    "zonas": [
      "Passeig del Born",
      "Santa Maria del Mar",
      "Sant Pere",
      "Palau de la Música"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/born1.jpg",
    "cardTeaser": "¿Vendes tu piso en el Born o Sant Pere? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-piso-ciutat-vella-barcelona": {
    "slug": "vender-piso-ciutat-vella-barcelona",
    "cluster": "barrio",
    "barrio": "Ciutat Vella",
    "footerLabel": "Vender en Ciutat Vella",
    "zonas": [
      "Gòtic",
      "Born",
      "Raval",
      "Barceloneta"
    ],
    "priority": 0.9,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/ciutatvella2.jpg",
    "cardTeaser": "¿Vendes tu piso en Ciutat Vella? Guía por barrios (Gòtic, Born, Raval, Barceloneta)."
  },
  "vender-piso-gotic-barcelona": {
    "slug": "vender-piso-gotic-barcelona",
    "cluster": "barrio",
    "barrio": "Gòtic",
    "footerLabel": "Vender en el Gòtic",
    "zonas": [
      "Plaça Sant Jaume",
      "Plaça Reial",
      "Carrer del Call",
      "Catedral"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/gotic1.jpg",
    "cardTeaser": "¿Vendes tu piso en el Barri Gòtic? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-piso-raval-barcelona": {
    "slug": "vender-piso-raval-barcelona",
    "cluster": "barrio",
    "barrio": "Raval",
    "footerLabel": "Vender en el Raval",
    "zonas": [
      "Rambla del Raval",
      "MACBA",
      "Sant Antoni (límite)",
      "Carrer Tallers"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/raval1.jpg",
    "cardTeaser": "¿Vendes tu piso en el Raval? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-poble-sec": {
    "slug": "vender-poble-sec",
    "cluster": "barrio",
    "barrio": "Poble Sec",
    "footerLabel": "Vender en Poble Sec",
    "zonas": [
      "Avinguda del Paral·lel",
      "Falda de Montjuïc",
      "Parc de les Tres Xemeneies",
      "Plaça del Sortidor"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/poblesec1.jpg",
    "cardTeaser": "¿Vendes tu piso en Poble Sec? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-poblenou": {
    "slug": "vender-poblenou",
    "cluster": "barrio",
    "barrio": "Poblenou",
    "footerLabel": "Vender en Poblenou",
    "zonas": [
      "Rambla del Poblenou",
      "Vila Olímpica",
      "Diagonal Mar",
      "Poblenou industrial",
      "Plaça de la Primera Junta"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/poblenou1.jpeg",
    "cardTeaser": "¿Vendes tu piso en Poblenou o Vila Olímpica? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-sant-andreu": {
    "slug": "vender-sant-andreu",
    "cluster": "barrio",
    "barrio": "Sant Andreu",
    "footerLabel": "Vender en Sant Andreu",
    "zonas": [
      "Sant Andreu de Palomar",
      "Congrés-Indians",
      "Bon Pastor",
      "Baró de Viver",
      "Fabra i Coats"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/barcelona5.jpg",
    "cardTeaser": "¿Vendes tu piso en Sant Andreu de Palomar? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-sant-antoni": {
    "slug": "vender-sant-antoni",
    "cluster": "barrio",
    "barrio": "Sant Antoni",
    "footerLabel": "Vender en Sant Antoni",
    "zonas": [
      "Mercat de Sant Antoni",
      "Ronda de Sant Antoni",
      "Carrer Comte Borrell",
      "Superilla de Sant Antoni"
    ],
    "priority": 0.87,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/eixample2.jpg",
    "cardTeaser": "¿Vendes tu piso en Sant Antoni? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-sant-gervasi": {
    "slug": "vender-sant-gervasi",
    "cluster": "barrio",
    "barrio": "Sant Gervasi",
    "footerLabel": "Vender en Sant Gervasi",
    "zonas": [
      "El Putxet",
      "El Farró",
      "Via Augusta",
      "Muntaner alto"
    ],
    "priority": 0.87,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/eixample4.jpg",
    "cardTeaser": "¿Vendes tu piso en Sant Gervasi (El Putxet, El Farró, Via Augusta)? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-sant-just-sant-joan-despi": {
    "slug": "vender-sant-just-sant-joan-despi",
    "cluster": "barrio",
    "barrio": "Sant Just Desvern y Sant Joan Despí",
    "footerLabel": "Vender en Sant Just / Sant Joan Despí",
    "zonas": [
      "Sant Just Centre",
      "La Bonaigua",
      "Sant Joan Despí Centre",
      "Riera de Sant Joan Despí",
      "Fontsanta"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/santjust1.webp",
    "cardTeaser": "¿Vendes en Sant Just Desvern o Sant Joan Despí? Honorarios fijos 3.000€ + IVA desde nuestra oficina en Les Corts."
  },
  "vender-sant-marti": {
    "slug": "vender-sant-marti",
    "cluster": "barrio",
    "barrio": "Sant Martí",
    "footerLabel": "Vender en Sant Martí",
    "zonas": [
      "Poblenou",
      "El Clot",
      "La Sagrera",
      "Diagonal Mar",
      "22@",
      "El Besòs"
    ],
    "priority": 0.87,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/interior11.jpg",
    "cardTeaser": "¿Vendes en Sant Martí? Poblenou, El Clot, 22@ ~3.900–5.200 €/m²."
  },
  "vender-sants": {
    "slug": "vender-sants",
    "cluster": "barrio",
    "barrio": "Sants",
    "footerLabel": "Vender en Sants",
    "zonas": [
      "Hostafrancs",
      "La Bordeta",
      "Estació de Sants",
      "Sants centre"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": true,
    "cardImage": "imagenes/sants1.jpg",
    "cardTeaser": "¿Vendes tu piso en Sants? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "vender-sarria": {
    "slug": "vender-sarria",
    "cluster": "barrio",
    "barrio": "Sarrià",
    "footerLabel": "Vender en Sarrià",
    "zonas": [
      "Galvany",
      "Bonanova",
      "Tres Torres",
      "Sarrià poble",
      "Vallvidrera"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/eixample5.jpg",
    "cardTeaser": "¿Vendes tu piso en Sarrià? NuevaHabitat: honorarios fijos de 3.000€ + IVA."
  },
  "cuanto-vale-mi-piso-barcelona": {
    "slug": "cuanto-vale-mi-piso-barcelona",
    "cluster": "situacion",
    "footerLabel": "Cuánto vale mi piso",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "cuanto vale mi piso barcelona",
    "badge": "Valoración gratuita · Sin compromiso",
    "testimonials": false,
    "cardImage": "imagenes/interior13.jpg",
    "cardTeaser": "Descubre cuánto vale tu piso en Barcelona con una valoración gratuita basada en comparables reales, no en e…"
  },
  "vender-piso-alquilado-barcelona": {
    "slug": "vender-piso-alquilado-barcelona",
    "cluster": "situacion",
    "footerLabel": "Vender piso alquilado",
    "priority": 0.87,
    "indexable": true,
    "keyword_principal": "vender piso alquilado barcelona",
    "badge": "Situación · Piso con inquilino",
    "testimonials": false,
    "cardImage": "imagenes/interior4.jpg",
    "cardTeaser": "¿Vendes un piso con inquilino en Barcelona? Te explicamos contrato en vigor, derecho de tanteo, visitas y p…"
  },
  "vender-piso-antes-comprar-otro-barcelona": {
    "slug": "vender-piso-antes-comprar-otro-barcelona",
    "cluster": "situacion",
    "footerLabel": "Vender antes de comprar",
    "priority": 0.87,
    "indexable": true,
    "keyword_principal": "vender piso antes de comprar otro barcelona",
    "badge": "Situación · Venta + compra",
    "testimonials": false,
    "cardImage": "imagenes/familia3.jpg",
    "cardTeaser": "¿Vendes en Barcelona para comprar otra vivienda? Sincroniza plazos, arras, hipoteca y entrega de llaves."
  },
  "vender-piso-herencia-barcelona": {
    "slug": "vender-piso-herencia-barcelona",
    "cluster": "situacion",
    "footerLabel": "Vender piso heredado",
    "priority": 0.88,
    "indexable": true,
    "keyword_principal": "vender piso herencia barcelona",
    "badge": "Situación · Piso heredado",
    "testimonials": false,
    "cardImage": "imagenes/familia2.jpg",
    "cardTeaser": "¿Has heredado un piso en Barcelona y quieres venderlo? Te explicamos aceptación de herencia, plusvalía, IRP…"
  },
  "vender-piso-hipoteca-pendiente-barcelona": {
    "slug": "vender-piso-hipoteca-pendiente-barcelona",
    "cluster": "situacion",
    "footerLabel": "Hipoteca pendiente",
    "priority": 0.87,
    "indexable": true,
    "keyword_principal": "vender piso con hipoteca pendiente barcelona",
    "badge": "Situación · Hipoteca pendiente",
    "testimonials": false,
    "cardImage": "imagenes/firma1.jpg",
    "cardTeaser": "¿Puedes vender un piso con hipoteca pendiente en Barcelona? Te explicamos cancelación registral, subrogació…"
  },
  "vender-piso-inquilino-vencer-barcelona": {
    "slug": "vender-piso-inquilino-vencer-barcelona",
    "cluster": "situacion",
    "footerLabel": "Inquilino vence pronto",
    "priority": 0.86,
    "indexable": true,
    "keyword_principal": "vender piso inquilino contrato vencer barcelona",
    "badge": "Situación · Contrato por vencer",
    "testimonials": false,
    "cardImage": "imagenes/interior9.jpg",
    "cardTeaser": "¿Vendes en Barcelona y el contrato de alquiler vence pronto? Planifica entrega de llaves, visitas, precio y compradores."
  },
  "vender-piso-okupado-barcelona": {
    "slug": "vender-piso-okupado-barcelona",
    "cluster": "situacion",
    "footerLabel": "Piso ocupado",
    "priority": 0.86,
    "indexable": true,
    "keyword_principal": "vender piso okupado barcelona",
    "badge": "Situación · Piso ocupado",
    "testimonials": false,
    "cardImage": "imagenes/interior8.jpg",
    "cardTeaser": "¿Tienes un piso ocupado en Barcelona y quieres venderlo? Te explicamos las opciones legales y de mercado, c…"
  },
  "vender-piso-separacion-divorcio-barcelona": {
    "slug": "vender-piso-separacion-divorcio-barcelona",
    "cluster": "situacion",
    "footerLabel": "Separación / divorcio",
    "priority": 0.87,
    "indexable": true,
    "keyword_principal": "vender piso separacion divorcio barcelona",
    "badge": "Situación · Separación o divorcio",
    "testimonials": false,
    "cardImage": "imagenes/familia5.jpg",
    "cardTeaser": "¿Vendes un piso tras una separación o divorcio en Barcelona? Te explicamos reparto del precio, hipoteca com…"
  },
  "vender-piso-traslado-barcelona": {
    "slug": "vender-piso-traslado-barcelona",
    "cluster": "situacion",
    "footerLabel": "Traslado / mudanza",
    "priority": 0.87,
    "indexable": true,
    "keyword_principal": "vender piso traslado trabajo barcelona",
    "badge": "Situación · Traslado / mudanza",
    "testimonials": false,
    "cardImage": "imagenes/barcelona7.webp",
    "cardTeaser": "¿Te mudas y vendes tu piso en Barcelona? Traslado laboral, expatriación o cambio de ciudad."
  },
  "vender-segunda-residencia-barcelona": {
    "slug": "vender-segunda-residencia-barcelona",
    "cluster": "situacion",
    "footerLabel": "Segunda residencia",
    "priority": 0.86,
    "indexable": true,
    "keyword_principal": "vender segunda residencia barcelona",
    "badge": "Situación · Piso vacío / 2ª residencia",
    "testimonials": false,
    "cardImage": "imagenes/interior12.webp",
    "cardTeaser": "¿Vendes un piso vacío o segunda residencia en Barcelona? Fiscalidad distinta, visitas flexibles y comprador…"
  },
  "inmobiliaria-precio-fijo-badalona-barcelona": {
    "slug": "inmobiliaria-precio-fijo-badalona-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Badalona",
    "priority": 0.88,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo badalona barcelona",
    "badge": "Badalona · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/interior11.jpg",
    "cardTeaser": "Inmobiliaria con precio fijo en Badalona: 3.000€ + IVA solo en escritura."
  },
  "inmobiliaria-precio-fijo-barcelona": {
    "slug": "inmobiliaria-precio-fijo-barcelona",
    "cluster": "intencion",
    "footerLabel": "Inmobiliaria precio fijo",
    "priority": 0.92,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo barcelona",
    "badge": "Barcelona · Precio fijo · Panel vendedor",
    "testimonials": false,
    "cardImage": "imagenes/comercial2.jpg",
    "cardTeaser": "Agencia en Barcelona con honorarios fijos 3.000€ + IVA solo al vender."
  },
  "inmobiliaria-precio-fijo-ciutat-vella-barcelona": {
    "slug": "inmobiliaria-precio-fijo-ciutat-vella-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Ciutat Vella",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo ciutat vella barcelona",
    "badge": "Ciutat Vella · Centro histórico",
    "testimonials": false,
    "cardImage": "imagenes/ciutatvella2.jpg",
    "cardTeaser": "Agencia honorarios fijos Ciutat Vella: Gòtic, Born, Raval, Barceloneta."
  },
  "inmobiliaria-precio-fijo-cornella-barcelona": {
    "slug": "inmobiliaria-precio-fijo-cornella-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Cornellà",
    "priority": 0.88,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo cornella barcelona",
    "badge": "Cornellà · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/barcelona1.jpeg",
    "cardTeaser": "Inmobiliaria con precio fijo en Cornellà: 3.000€ + IVA solo en escritura."
  },
  "inmobiliaria-precio-fijo-eixample-barcelona": {
    "slug": "inmobiliaria-precio-fijo-eixample-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Eixample",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo eixample barcelona",
    "badge": "Eixample · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/eixample1.jpg",
    "cardTeaser": "Inmobiliaria con precio fijo en Eixample: 3.000€ + IVA solo en escritura."
  },
  "inmobiliaria-precio-fijo-el-clot-barcelona": {
    "slug": "inmobiliaria-precio-fijo-el-clot-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo El Clot",
    "priority": 0.89,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo el clot barcelona",
    "badge": "El Clot · La Sagrera · 08018",
    "testimonials": false,
    "cardImage": "imagenes/santmarti1.webp",
    "cardTeaser": "Agencia precio fijo El Clot, La Sagrera, Sant Martí de Provençals."
  },
  "inmobiliaria-precio-fijo-esplugues-barcelona": {
    "slug": "inmobiliaria-precio-fijo-esplugues-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Esplugues",
    "priority": 0.88,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo esplugues barcelona",
    "badge": "Esplugues · Área metropolitana · 08950",
    "testimonials": false,
    "cardImage": "imagenes/esplugues1.jpg",
    "cardTeaser": "Agencia precio fijo Esplugues de Llobregat (08950)."
  },
  "inmobiliaria-precio-fijo-gracia-barcelona": {
    "slug": "inmobiliaria-precio-fijo-gracia-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Gràcia",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo gracia barcelona",
    "badge": "Gràcia · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/gracia1.jpg",
    "cardTeaser": "Inmobiliaria con precio fijo en Gràcia: 3.000€ + IVA solo en escritura."
  },
  "inmobiliaria-precio-fijo-horta-barcelona": {
    "slug": "inmobiliaria-precio-fijo-horta-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Horta",
    "priority": 0.89,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo horta barcelona",
    "badge": "Horta-Guinardó · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/horta1.jpg",
    "cardTeaser": "Inmobiliaria con precio fijo en Horta-Guinardó: 3.000€ + IVA solo en escritura."
  },
  "inmobiliaria-precio-fijo-l-hospitalet-barcelona": {
    "slug": "inmobiliaria-precio-fijo-l-hospitalet-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo L'Hospitalet",
    "priority": 0.88,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo l hospitalet barcelona",
    "badge": "L'Hospitalet · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/hospitalet1.jpg",
    "cardTeaser": "Inmobiliaria con precio fijo en L'Hospitalet: 3.000€ + IVA solo en escritura."
  },
  "inmobiliaria-precio-fijo-les-corts-barcelona": {
    "slug": "inmobiliaria-precio-fijo-les-corts-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Les Corts",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo les corts barcelona",
    "badge": "Les Corts · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/lescorts1.jpg",
    "cardTeaser": "Inmobiliaria con precio fijo en Les Corts: 3.000€ + IVA solo en escritura."
  },
  "inmobiliaria-precio-fijo-nou-barris-barcelona": {
    "slug": "inmobiliaria-precio-fijo-nou-barris-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Nou Barris",
    "priority": 0.89,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo nou barris barcelona",
    "badge": "Nou Barris · Primera vivienda · Metro",
    "testimonials": false,
    "cardImage": "imagenes/noubarris1.jpg",
    "cardTeaser": "Agencia honorarios fijos Nou Barris (2.900–3.400 €/m²)."
  },
  "inmobiliaria-precio-fijo-poble-sec-barcelona": {
    "slug": "inmobiliaria-precio-fijo-poble-sec-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Poble Sec",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo poble sec barcelona",
    "badge": "Poble Sec · Precio fijo · 08004",
    "testimonials": false,
    "cardImage": "imagenes/poblesec1.jpg",
    "cardTeaser": "Landing intención: agencia honorarios fijos en Poble Sec (08004)."
  },
  "inmobiliaria-precio-fijo-poblenou-barcelona": {
    "slug": "inmobiliaria-precio-fijo-poblenou-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Poblenou",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo poblenou barcelona",
    "badge": "Poblenou · 22@ · Mar",
    "testimonials": false,
    "cardImage": "imagenes/poblenou1.jpeg",
    "cardTeaser": "Agencia precio fijo Poblenou, Vila Olímpica, Rambla, 22@."
  },
  "inmobiliaria-precio-fijo-sant-andreu-barcelona": {
    "slug": "inmobiliaria-precio-fijo-sant-andreu-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Sant Andreu",
    "priority": 0.89,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo sant andreu barcelona",
    "badge": "Sant Andreu · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/barcelona5.jpg",
    "cardTeaser": "Inmobiliaria con precio fijo en Sant Andreu: 3.000€ + IVA solo en escritura."
  },
  "inmobiliaria-precio-fijo-sant-antoni-barcelona": {
    "slug": "inmobiliaria-precio-fijo-sant-antoni-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Sant Antoni",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo sant antoni barcelona",
    "badge": "Sant Antoni · Precio fijo · Panel",
    "testimonials": false,
    "cardImage": "imagenes/eixample2.jpg",
    "cardTeaser": "Honorarios fijos en Sant Antoni: 3.000€ + IVA solo al vender, no 6%."
  },
  "inmobiliaria-precio-fijo-sant-gervasi-barcelona": {
    "slug": "inmobiliaria-precio-fijo-sant-gervasi-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Sant Gervasi",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo sant gervasi barcelona",
    "badge": "Sant Gervasi · Putxet · Via Augusta",
    "testimonials": false,
    "cardImage": "imagenes/eixample4.jpg",
    "cardTeaser": "Agencia honorarios fijos Sant Gervasi (Putxet, Farró, Via Augusta)."
  },
  "inmobiliaria-precio-fijo-sants-barcelona": {
    "slug": "inmobiliaria-precio-fijo-sants-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Sants",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo sants barcelona",
    "badge": "Sants · Precio fijo · Panel vendedor",
    "testimonials": false,
    "cardImage": "imagenes/sants1.jpg",
    "cardTeaser": "Agencia con honorarios fijos en Sants: 3.000€ + IVA solo al vender, no un 6%."
  },
  "inmobiliaria-precio-fijo-sarria-barcelona": {
    "slug": "inmobiliaria-precio-fijo-sarria-barcelona",
    "cluster": "intencion",
    "footerLabel": "Precio fijo Sarrià",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "inmobiliaria precio fijo sarria barcelona",
    "badge": "Sarrià · Precio fijo · Panel",
    "testimonials": false,
    "cardImage": "imagenes/eixample5.jpg",
    "cardTeaser": "Vender en Sarrià, Bonanova o Tres Torres con honorarios fijos 3.000€ + IVA solo en escritura."
  },
  "vender-piso-rapido-barcelona": {
    "slug": "vender-piso-rapido-barcelona",
    "cluster": "intencion",
    "footerLabel": "Vender piso rápido",
    "priority": 0.89,
    "indexable": true,
    "keyword_principal": "vender piso rapido barcelona",
    "badge": "Urgencia · Venta ágil",
    "testimonials": false,
    "cardImage": "imagenes/comercial2.jpg",
    "cardTeaser": "¿Necesitas vender tu piso rápido en Barcelona? Calcula tu ahorro, compara modelos (agencia, particular, por…"
  },
  "vender-piso-sin-exclusividad-barcelona": {
    "slug": "vender-piso-sin-exclusividad-barcelona",
    "cluster": "intencion",
    "footerLabel": "Vender sin exclusividad",
    "priority": 0.89,
    "indexable": true,
    "keyword_principal": "vender piso sin exclusividad barcelona",
    "badge": "Particular · Sin exclusiva",
    "testimonials": false,
    "cardImage": "imagenes/agente inmobiliario2.jpg",
    "cardTeaser": "¿Quieres vender tu piso en Barcelona sin exclusiva ni permanencia abusiva? Guía para particulares: compara …"
  },
  "venta-piso-economica-barcelona": {
    "slug": "venta-piso-economica-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Barcelona",
    "priority": 0.93,
    "indexable": true,
    "keyword_principal": "venta de piso economica barcelona",
    "badge": "Barcelona · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/familia10.jpg",
    "cardTeaser": "Vende tu piso en Barcelona con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-eixample-barcelona": {
    "slug": "venta-piso-economica-eixample-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Eixample",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica eixample barcelona",
    "badge": "Eixample · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/eixample1.jpg",
    "cardTeaser": "Vende tu piso en Eixample con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-gracia-barcelona": {
    "slug": "venta-piso-economica-gracia-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Gràcia",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica gràcia barcelona",
    "badge": "Gràcia · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/gracia1.jpg",
    "cardTeaser": "Vende tu piso en Gràcia con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-horta-barcelona": {
    "slug": "venta-piso-economica-horta-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Horta-Guinardó",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica horta-guinardó barcelona",
    "badge": "Horta-Guinardó · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/horta1.jpg",
    "cardTeaser": "Vende tu piso en Horta-Guinardó con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-l-hospitalet-barcelona": {
    "slug": "venta-piso-economica-l-hospitalet-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica L'Hospitalet",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica l'hospitalet barcelona",
    "badge": "L'Hospitalet · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/hospitalet1.jpg",
    "cardTeaser": "Vende tu piso en L'Hospitalet con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-les-corts-barcelona": {
    "slug": "venta-piso-economica-les-corts-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Les Corts",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica les corts barcelona",
    "badge": "Les Corts · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/lescorts1.jpg",
    "cardTeaser": "Vende tu piso en Les Corts con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-poblenou-barcelona": {
    "slug": "venta-piso-economica-poblenou-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Poblenou",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica poblenou barcelona",
    "badge": "Poblenou · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/poblenou1.jpeg",
    "cardTeaser": "Vende tu piso en Poblenou con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-sant-antoni-barcelona": {
    "slug": "venta-piso-economica-sant-antoni-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Sant Antoni",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica sant antoni barcelona",
    "badge": "Sant Antoni · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/eixample2.jpg",
    "cardTeaser": "Vende tu piso en Sant Antoni con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-sant-marti-barcelona": {
    "slug": "venta-piso-economica-sant-marti-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Sant Martí",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica sant martí barcelona",
    "badge": "Sant Martí · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/interior11.jpg",
    "cardTeaser": "Vende tu piso en Sant Martí con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-sants-barcelona": {
    "slug": "venta-piso-economica-sants-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Sants",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica sants barcelona",
    "badge": "Sants · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/sants1.jpg",
    "cardTeaser": "Vende tu piso en Sants con honorarios fijos 3.630 € (solo en escritura)."
  },
  "venta-piso-economica-sarria-barcelona": {
    "slug": "venta-piso-economica-sarria-barcelona",
    "cluster": "intencion",
    "footerLabel": "Venta económica Sarrià",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "venta de piso economica sarrià barcelona",
    "badge": "Sarrià · Venta económica · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/eixample5.jpg",
    "cardTeaser": "Vende tu piso en Sarrià con honorarios fijos 3.630 € (solo en escritura)."
  },
  "vender-como-particular-badalona-barcelona": {
    "slug": "vender-como-particular-badalona-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Badalona",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular badalona",
    "badge": "Badalona · 08911 · Particular",
    "testimonials": false,
    "cardImage": "imagenes/interior11.jpg",
    "cardTeaser": "Guía particular Badalona: 2.650 – 3.100 €/m² (Centre · Gorg · Montigalà)."
  },
  "vender-como-particular-barcelona": {
    "slug": "vender-como-particular-barcelona",
    "cluster": "particular",
    "footerLabel": "Vender como particular",
    "priority": 0.93,
    "indexable": true,
    "keyword_principal": "vender piso particular barcelona",
    "badge": "Barcelona · Particular vendedor · Precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/comercial2.jpg",
    "cardTeaser": "Guía para propietarios que venden por su cuenta en Barcelona: documentos, errores típicos, visitas con crit…"
  },
  "vender-como-particular-ciutat-vella-barcelona": {
    "slug": "vender-como-particular-ciutat-vella-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Ciutat Vella",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "vender piso particular ciutat vella barcelona",
    "badge": "Ciutat Vella · Gòtic · Born · Raval · Barceloneta",
    "testimonials": false,
    "cardImage": "imagenes/ciutatvella2.jpg",
    "cardTeaser": "Guía particular en Ciutat Vella: cuatro barrios, precios 3.000–6.900 €/m², licencias, herencias y comprador…"
  },
  "vender-como-particular-cornella-barcelona": {
    "slug": "vender-como-particular-cornella-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Cornellà",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular cornella",
    "badge": "Cornellà · 08940 · Particular",
    "testimonials": false,
    "cardImage": "imagenes/barcelona1.jpeg",
    "cardTeaser": "Guía particular Cornellà de Llobregat: 2.600 – 3.100 €/m² (Centre · Sant Ildefons · Almeda)."
  },
  "vender-como-particular-eixample-barcelona": {
    "slug": "vender-como-particular-eixample-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Eixample",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular eixample barcelona",
    "badge": "Eixample · Finca · Particular vendedor",
    "testimonials": false,
    "cardImage": "imagenes/eixample1.jpg",
    "cardTeaser": "Guía particular Eixample: Dreta, Esquerra, Sant Antoni, Fort Pienc."
  },
  "vender-como-particular-esplugues-barcelona": {
    "slug": "vender-como-particular-esplugues-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Esplugues",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular esplugues",
    "badge": "Esplugues · 08950 · Particular",
    "testimonials": false,
    "cardImage": "imagenes/esplugues1.jpg",
    "cardTeaser": "Guía particular Esplugues de Llobregat: 3.200 – 3.800 €/m² (Can Vidalet · Centre · Finestrelles)."
  },
  "vender-como-particular-gracia-barcelona": {
    "slug": "vender-como-particular-gracia-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Gràcia",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular gracia barcelona",
    "badge": "Gràcia · Plazas · Particular vendedor",
    "testimonials": false,
    "cardImage": "imagenes/gracia1.jpg",
    "cardTeaser": "Guía particular Gràcia: Vila, Camp d'en Grassot, Vallcarca."
  },
  "vender-como-particular-horta-barcelona": {
    "slug": "vender-como-particular-horta-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Horta-Guinardó",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular horta barcelona",
    "badge": "Horta-Guinardó · 08031 · Particular",
    "testimonials": false,
    "cardImage": "imagenes/horta1.jpg",
    "cardTeaser": "Guía particular Horta-Guinardó: 3.900 – 4.300 €/m² (Horta · Montbau · Guinardó)."
  },
  "vender-como-particular-l-hospitalet-barcelona": {
    "slug": "vender-como-particular-l-hospitalet-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular L'Hospitalet",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular l hospitalet",
    "badge": "L'Hospitalet · 08901 · Particular",
    "testimonials": false,
    "cardImage": "imagenes/hospitalet1.jpg",
    "cardTeaser": "Guía particular L'Hospitalet de Llobregat: 2.750 – 3.200 €/m² (Centre · Bellvitge · Pubilla)."
  },
  "vender-como-particular-les-corts-barcelona": {
    "slug": "vender-como-particular-les-corts-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Les Corts",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "vender piso particular les corts barcelona",
    "badge": "Les Corts · Particular vendedor · Oficina NH",
    "testimonials": false,
    "cardImage": "imagenes/lescorts1.jpg",
    "cardTeaser": "Guía para propietarios en Les Corts (Numància, Pedralbes, Zona Universitaria): precios 4.700–6.200 €/m², er…"
  },
  "vender-como-particular-poblenou-barcelona": {
    "slug": "vender-como-particular-poblenou-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Poblenou",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular poblenou barcelona",
    "badge": "Poblenou · Mar · 22@ · Particular",
    "testimonials": false,
    "cardImage": "imagenes/poblenou1.jpeg",
    "cardTeaser": "Guía particular Poblenou: Rambla, 22@, lofts, Diagonal Mar."
  },
  "vender-como-particular-sant-andreu-barcelona": {
    "slug": "vender-como-particular-sant-andreu-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Sant Andreu",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular sant andreu barcelona",
    "badge": "Sant Andreu · 08030 · Particular",
    "testimonials": false,
    "cardImage": "imagenes/barcelona5.jpg",
    "cardTeaser": "Guía particular Sant Andreu: 3.100 – 4.000 €/m² (Palomar · Congrés · Fabra i Coats)."
  },
  "vender-como-particular-sant-antoni-barcelona": {
    "slug": "vender-como-particular-sant-antoni-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Sant Antoni",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular sant antoni barcelona",
    "badge": "Sant Antoni · 08015 · Particular",
    "testimonials": false,
    "cardImage": "imagenes/eixample2.jpg",
    "cardTeaser": "Guía particular Sant Antoni: 4.700 – 5.900 €/m² (Superilla · Mercat · Comte Borrell)."
  },
  "vender-como-particular-sant-marti-barcelona": {
    "slug": "vender-como-particular-sant-marti-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Sant Martí",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular sant marti barcelona",
    "badge": "Sant Martí · 08005 · Particular",
    "testimonials": false,
    "cardImage": "imagenes/interior11.jpg",
    "cardTeaser": "Guía particular Sant Martí: 3.900 – 5.200 €/m² (Poblenou · Clot · 22@ · Besòs)."
  },
  "vender-como-particular-sants-barcelona": {
    "slug": "vender-como-particular-sants-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Sants",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular sants barcelona",
    "badge": "Sants · 08014 · Particular vendedor",
    "testimonials": false,
    "cardImage": "imagenes/sants1.jpg",
    "cardTeaser": "Guía particular Sants: Hostafrancs, La Bordeta, Estació."
  },
  "vender-como-particular-sarria-barcelona": {
    "slug": "vender-como-particular-sarria-barcelona",
    "cluster": "particular",
    "footerLabel": "Particular Sarrià",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "vender piso particular sarria barcelona",
    "badge": "Sarrià · Premium · Particular vendedor",
    "testimonials": false,
    "cardImage": "imagenes/eixample5.jpg",
    "cardTeaser": "Guía particular Sarrià: Bonanova, Galvany, Tres Torres."
  },
  "nuevahabitat-vs-agencia-tradicional-barcelona": {
    "slug": "nuevahabitat-vs-agencia-tradicional-barcelona",
    "cluster": "comparativa",
    "footerLabel": "NH vs agencia 6%",
    "priority": 0.91,
    "indexable": true,
    "keyword_principal": "comision inmobiliaria barcelona vs precio fijo",
    "badge": "Comparativa · 6% vs 3.000€ fijos",
    "testimonials": false,
    "cardImage": "imagenes/equipo1.jpg",
    "cardTeaser": "¿Cuánto cobra una inmobiliaria en Barcelona? Compara comisión del 6% + IVA vs precio fijo 3.000€ + IVA de NuevaHabitat."
  },
  "nuevahabitat-vs-clikalia-barcelona": {
    "slug": "nuevahabitat-vs-clikalia-barcelona",
    "cluster": "comparativa",
    "footerLabel": "NH vs Clikalia",
    "priority": 0.87,
    "indexable": true,
    "keyword_principal": "nuevahabitat vs clikalia barcelona",
    "badge": "Comparativa · Venta instantánea vs precio de mercado",
    "testimonials": false,
    "cardImage": "imagenes/inmobiliario4.jpg",
    "cardTeaser": "¿Vender a un comprador instantáneo como Clikalia o con NuevaHabitat? Compara el descuento del iBuyer frente…"
  },
  "nuevahabitat-vs-fotocasa-particular": {
    "slug": "nuevahabitat-vs-fotocasa-particular",
    "cluster": "comparativa",
    "footerLabel": "NH vs Fotocasa",
    "priority": 0.89,
    "indexable": true,
    "keyword_principal": "nuevahabitat vs fotocasa particular",
    "badge": "Comparativa · Fotocasa vs precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/interior5.jpg",
    "cardTeaser": "¿Vender en Fotocasa como particular o con NuevaHabitat en Barcelona? Coste del anuncio, filtro de comprador…"
  },
  "nuevahabitat-vs-housfy-barcelona": {
    "slug": "nuevahabitat-vs-housfy-barcelona",
    "cluster": "comparativa",
    "footerLabel": "NH vs Housfy",
    "priority": 0.87,
    "indexable": true,
    "keyword_principal": "nuevahabitat vs housfy barcelona",
    "badge": "Comparativa · Dos modelos de precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/inmobiliario2.jpg",
    "cardTeaser": "¿Housfy o NuevaHabitat para vender tu piso en Barcelona? Compara acompañamiento local, visitas presenciales…"
  },
  "nuevahabitat-vs-idealista-particular": {
    "slug": "nuevahabitat-vs-idealista-particular",
    "cluster": "comparativa",
    "footerLabel": "NH vs Idealista",
    "priority": 0.9,
    "indexable": true,
    "keyword_principal": "nuevahabitat vs idealista particular",
    "badge": "Comparativa · Particular vs precio fijo",
    "testimonials": false,
    "cardImage": "imagenes/comercial1.jpg",
    "cardTeaser": "¿Vender en Idealista como particular o con NuevaHabitat? Compara coste real, filtro de compradores, negocia…"
  },
  "vender-por-tu-cuenta-vs-nuevahabitat-barcelona": {
    "slug": "vender-por-tu-cuenta-vs-nuevahabitat-barcelona",
    "cluster": "comparativa",
    "footerLabel": "Por tu cuenta vs NH",
    "priority": 0.88,
    "indexable": true,
    "keyword_principal": "vender piso por tu cuenta vs inmobiliaria barcelona",
    "badge": "Comparativa · Solo vs acompañado",
    "testimonials": false,
    "cardImage": "imagenes/familia1.jpg",
    "cardTeaser": "¿Vender el piso solo o con NuevaHabitat en Barcelona? Compara tiempo, riesgos legales, filtro de compradore…"
  },
  "comprar-piso-badalona-barcelona": {
    "slug": "comprar-piso-badalona-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Badalona",
    "footerLabel": "Comprar en Badalona",
    "zonas": [
      "Centre",
      "Gorg",
      "Montigalà",
      "La Salut",
      "Sant Roc",
      "Artigues"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/interior11.jpg",
    "cardTeaser": "Guía comprador Badalona: elige barrio (no solo municipio), negocia con datos, revisa ITE y arras, firma escritura."
  },
  "comprar-piso-barcelona": {
    "slug": "comprar-piso-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "footerLabel": "Comprar piso Barcelona",
    "priority": 0.9,
    "indexable": true,
    "testimonials": false,
    "badge": "Comprador · Barcelona",
    "cardImage": "imagenes/familia2.jpg",
    "cardTeaser": "¿Buscas comprar piso en Barcelona? NuevaHabitat te acompaña con honorarios fijos de 5.000€ + IVA, solo en escritura."
  },
  "comprar-piso-eixample-barcelona": {
    "slug": "comprar-piso-eixample-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Eixample",
    "footerLabel": "Comprar en el Eixample",
    "zonas": [
      "Eixample Derecho",
      "Eixample Esquerre",
      "Sagrada Família",
      "Passeig de Gràcia",
      "Fort Pienc",
      "Sant Antoni"
    ],
    "priority": 0.87,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/eixample1.jpg",
    "cardTeaser": "¿Quieres comprar piso en el Eixample? Acompañamiento comprador con 5.000€ + IVA solo en escritura."
  },
  "comprar-piso-esplugues-barcelona": {
    "slug": "comprar-piso-esplugues-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Esplugues de Llobregat",
    "footerLabel": "Comprar en Esplugues",
    "zonas": [
      "Can Vidalet",
      "Centre",
      "Finestrelles",
      "Les Malloles",
      "Can Sant Joan"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/esplugues1.jpg",
    "cardTeaser": "Familias entre Les Corts y Sarrià: guía comprador en Esplugues, bloques vs adosados, negociación, revisión …"
  },
  "comprar-piso-gracia-barcelona": {
    "slug": "comprar-piso-gracia-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Gràcia",
    "footerLabel": "Comprar en Gràcia",
    "zonas": [
      "Vila de Gràcia",
      "Camp d'en Grassot",
      "Vallcarca",
      "Penitents"
    ],
    "priority": 0.87,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/gracia1.jpg",
    "cardTeaser": "Comprar en Gràcia con guía experto: búsqueda de piso, negociación, revisión de documentación y trámites has…"
  },
  "comprar-piso-horta-barcelona": {
    "slug": "comprar-piso-horta-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Horta-Guinardó",
    "footerLabel": "Comprar en Horta-Guinardó",
    "zonas": [
      "Horta centre",
      "Montbau",
      "Vall d'Hebron",
      "La Teixonera",
      "El Carmel"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/horta1.jpg",
    "cardTeaser": "Familias en Horta: Montbau plano vs Teixonera con pendiente, negociación con comparables, revisión de terra…"
  },
  "comprar-piso-l-hospitalet-barcelona": {
    "slug": "comprar-piso-l-hospitalet-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "L'Hospitalet",
    "footerLabel": "Comprar en L'Hospitalet",
    "zonas": [
      "Centre",
      "Bellvitge",
      "Pubilla Cases",
      "Granvia L'H",
      "Santa Eulàlia"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/hospitalet1.jpg",
    "cardTeaser": "Más metros en L'Hospitalet con guía comprador: Centre vs Bellvitge, negociación en mercado de volumen, revi…"
  },
  "comprar-piso-les-corts-barcelona": {
    "slug": "comprar-piso-les-corts-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Les Corts",
    "footerLabel": "Comprar en Les Corts",
    "zonas": [
      "Numància",
      "Zona Universitaria",
      "Pedralbes",
      "Les Corts centre",
      "Entorno Camp Nou"
    ],
    "priority": 0.88,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/lescorts1.jpg",
    "cardTeaser": "NuevaHabitat acompaña al comprador en Les Corts de principio a fin: búsqueda de vivienda, negociación, revi…"
  },
  "comprar-piso-nou-barris-barcelona": {
    "slug": "comprar-piso-nou-barris-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Nou Barris",
    "footerLabel": "Comprar en Nou Barris",
    "zonas": [
      "Verdum",
      "Roquetes",
      "Trinitat Vella",
      "Porta",
      "Torre Baró"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/noubarris1.jpg",
    "cardTeaser": "Entrada a Barcelona ciudad en Nou Barris: bloques 60-70, metro L3/L4/L5, negociación con comparables, revis…"
  },
  "comprar-piso-poble-sec-barcelona": {
    "slug": "comprar-piso-poble-sec-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Poble Sec",
    "footerLabel": "Comprar en Poble Sec",
    "zonas": [
      "Paral·lel",
      "Falda de Montjuïc",
      "Tres Xemeneies",
      "Plaça del Sortidor"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/poblesec1.jpg",
    "cardTeaser": "Fincas sin ascensor, luz en calle estrecha y terraza con vistas: guía comprador Poble Sec, negociación, rev…"
  },
  "comprar-piso-poblenou-barcelona": {
    "slug": "comprar-piso-poblenou-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Poblenou",
    "footerLabel": "Comprar en Poblenou",
    "zonas": [
      "22@",
      "Vila Olímpica",
      "Rambla del Poblenou",
      "Diagonal Mar",
      "La Verneda"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/poblenou1.jpeg",
    "cardTeaser": "Comprar en Poblenou y 22@ con NuevaHabitat: búsqueda de vivienda, negociación, revisión documental y trámit…"
  },
  "comprar-piso-sant-andreu-barcelona": {
    "slug": "comprar-piso-sant-andreu-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Sant Andreu",
    "footerLabel": "Comprar en Sant Andreu",
    "zonas": [
      "Sant Andreu de Palomar",
      "Congrés-Indians",
      "Bon Pastor",
      "Baró de Viver",
      "Fabra i Coats"
    ],
    "priority": 0.85,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/barcelona5.jpg",
    "cardTeaser": "Pueblo dentro de Barcelona: guía comprador en Sant Andreu, regeneración Fabra i Coats, fincas sin ascensor …"
  },
  "comprar-piso-sant-antoni-barcelona": {
    "slug": "comprar-piso-sant-antoni-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Sant Antoni",
    "footerLabel": "Comprar en Sant Antoni",
    "zonas": [
      "Mercat de Sant Antoni",
      "Superilla peatonal",
      "Comte Borrell",
      "Ronda de Sant Antoni"
    ],
    "priority": 0.87,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/eixample2.jpg",
    "cardTeaser": "Mercado competitivo en Sant Antoni: calle peatonal vs ronda, finca modernista, negociación con comparables …"
  },
  "comprar-piso-sant-gervasi-barcelona": {
    "slug": "comprar-piso-sant-gervasi-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Sant Gervasi",
    "footerLabel": "Comprar en Sant Gervasi",
    "zonas": [
      "El Putxet",
      "El Farró",
      "Via Augusta",
      "Muntaner alto"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/eixample4.jpg",
    "cardTeaser": "Guía comprador en Sant Gervasi: micro-zonas Putxet y Farró, negociación con propietario, revisión de arras …"
  },
  "comprar-piso-sant-marti-barcelona": {
    "slug": "comprar-piso-sant-marti-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Sant Martí",
    "footerLabel": "Comprar en Sant Martí",
    "zonas": [
      "El Clot",
      "La Sagrera",
      "22@",
      "Diagonal Mar",
      "El Besòs"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/interior11.jpg",
    "cardTeaser": "Guía comprador Sant Martí: no confundas El Clot con Poblenou en precio."
  },
  "comprar-piso-sants-barcelona": {
    "slug": "comprar-piso-sants-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Sants",
    "footerLabel": "Comprar en Sants",
    "zonas": [
      "Hostafrancs",
      "La Bordeta",
      "Estació de Sants",
      "Sants centre"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/sants1.jpg",
    "cardTeaser": "Comprar en Sants con NuevaHabitat: te ayudamos a encontrar piso cerca de la estación, negociamos precio, re…"
  },
  "comprar-piso-sarria-barcelona": {
    "slug": "comprar-piso-sarria-barcelona",
    "cluster": "comprador",
    "audience": "comprador",
    "barrio": "Sarrià",
    "footerLabel": "Comprar en Sarrià",
    "zonas": [
      "Galvany",
      "Bonanova",
      "Tres Torres",
      "Sarrià poble",
      "Vallvidrera"
    ],
    "priority": 0.86,
    "indexable": true,
    "testimonials": false,
    "cardImage": "imagenes/eixample5.jpg",
    "cardTeaser": "Comprar en Sarrià, Bonanova o Tres Torres con guía experto: búsqueda discreta, negociación técnica, revisió…"
  }
};
Object.keys(window.NH_LANDINGS).forEach(function(slug){
  var c = window.NH_LANDINGS[slug].cluster;
  if (c && window.NH_LANDING_CLUSTERS[c]) window.NH_LANDING_CLUSTERS[c].slugs.push(slug);
});
window.NH_LANDING_SLUGS = window.NH_LANDING_ORDER.slice();
